### ISSUE TITLE
Issues when adding max-height and overflow-y to `Drawer.Content`

### ISSUE THREAD

**Issue by cljang** [emilkowalski/vaul#575]
Description:
I am noticing two issues when trying to cap drawer content with a max-height and adding overflow-y: auto

1. Drawer content ::after cuts off long content below the fold
2. Drawer dragging doesn't work when content is scrolled

Sandbox:
https://codesandbox.io/p/sandbox/f594kw

- Uncapped height is default behaviour with long content
- Capped height adds a max-height: 100vh and overflow-y: auto
- After override resets the ::after element height to unset

Steps to Reproduce:
1. Add a Drawer component with a Drawer.Content component inside. 
2. Add a long amount of content. 
3. Cap the max-height of the Drawer.Content such that it would cut off the content and add overflow-y: auto
4. Try scrolling and observe that below the fold is cut off by the ::after pseudo element
5. Also observe that the drawer can not be dragged until scrolling is returned to the top

Expected Behavior:
- Drawer shouldn't cut off content below the fold when setting a max-height and overflow-y behaviours
- Drawer should still be draggable when scrolled

Other Notes:
- I noticed that override the ::after element's height to be unset manually would fix the issue with cut off content (not sure if this has any knock on effects)

Not sure if I am just missing something obvious or if this is an actual bug.

**Comment by amirrezaDev1378** [comment]
I'm having this exact issue, not sure if it's safe to modify the height of ::after, isn't it there for a reason ?

**Comment by olssoncharlie** [comment]
Got this working by adding an empty div with `pb-[var(--snap-point-height)]` under the scroll container.

Basically when you use `snapPoints`, the drawer uses transform to offset the height to the snapPoint, `transform: translate3d(0, var(--snap-point-height), 0)`. The padding div adds the same height to our content, offsetting the invisible content

Scrolling still triggers the drawer to expand to the next snap point, but we use `handleOnly` to prevent that from happening.

```jsx
<DrawerPrimitive
    snapPoints={[0.5, 1]}
    handleOnly
>
    <DrawerPortal>
        <DrawerContent className="h-full max-h-[97%]">
            <DrawerHeader>
                {!!header && header}
                {!header && <DrawerHandle />}
            </DrawerHeader>
            <div className="h-full overflow-y-auto">{children}</div>
            {snapPoint !== 1 && <div className="pb-[var(--snap-point-height)]" />}
        </DrawerContent>
    </DrawerPortal>
</DrawerPrimitive>
```

**Comment by cljang** [comment]
I have an alternative handling where you use the `--snap-point-height` CSS var to set the height of an inner wrapper and setting `top: 0` (basically `inset: 0`) to position the drawer content. This also seems to get the positioning to be correct when using `snapPoints`. This also correctly sets the height for the overflow scrolling.

Since the `--snap-point-height` doesn't live update, there will be a gap at the bottom of the drawer when transitioning to a larger snapPoint. To address that, I have added an empty white div that can grow in the flex container. This visually makes the drawer extend to the bottom until the new snap point updates the height and it re-flows the content. This would not be necessary if we could access the live transform value.

<hr>

Demo
https://github.com/user-attachments/assets/1adf554f-242a-4b07-b391-3a3343c0add8

CSS
```css
.vaul-drawer-content-card {
  /* 1.5rem is the height of the handle at the top of the drawer */
  height: calc(100% - var(--snap-point-height) - 1.5rem);
}

[data-vaul-drawer] {
  /* When snap points are enabled, the drawer should be positioned at the top of the screen.
  This will ensure the positioning of the drawer stays correct */
  &[data-vaul-snap-points='true'].vaul-drawer-content {
    top: 0;
  }

  &[data-vaul-snap-points='false'] .vaul-drawer-content-bottom-padding {
    display: none;
  }
}
```

JS
```jsx
<DrawerPrimative snapPoints={[0.5, 1]}>
  <DrawerPortal>
    <DrawerOverlay />
    <DrawerPrimitive.Content
      className={'z-[1050] fixed inset-x-0 bottom-0 flex flex-col max-h-full vaul-drawer-content'}
    >
      {/* Handle - note that the total height of the handle should match the value set in the CSS */}
      <div className='my-2 mx-auto bg-gray-200 h-2 w-20 shrink-0 rounded-full' />
      <div
        className={'rounded-t p-4 bg-white rounded-b-none border border-b-0 overflow-y-auto vaul-drawer-content-card'}
      >
        {children}
      </div>
  
      {/* Bottom padding - this fills the spacing below the drawer when there are snap points, 
      this also visually extends the drawer when transitioning to larger snap points */}
      <div className='flex-1 w-full bg-white vaul-drawer-content-bottom-padding pointer-events-none'></div>
    </DrawerPrimitive.Content>
  </DrawerPortal>
</DrawerPrimative>
```
