### ISSUE TITLE
Remove default animations for custom animations

### ISSUE THREAD

**Issue by JeffreyJoumjian** [emilkowalski/vaul#87]
Hello I was wondering if there's a way to properly disable the default animations. I've been using this component as a base for our Drawer component and I absolutely love it since it fits most our needs. I've added the ability to position the components on different parts of the screen `"top" | "right" | "bottom" | "left"` and have added the styles for it, however i would like to also add the corresponding sliding animations. (when positioned at top, it should slide in from the top etc...) 

The problem is that the `[vaul-drawer]` and `[vaul-drawer][data-state="closed"]` css classes are taking priority over my own styles, and if i try to set `"animation: none"` on the component, that rule is always taking priority and no new animations are being applied. However, if I try to add my own animations without removing the default vaul animations using `"animation: none"`, some of the vaul-animation settings like duration or transform, which my animation styles may not override are still being applied. 

I know in the future you might add the positioning as a feature yourself but is there a way to remove the default animations instead of manually overriding all the css properties set by `[vaul-drawer]` and `[vaul-drawer][data-state="open"]` classes? any advice is appreciated.

**Comment by JeffreyJoumjian** [comment]
This was my solution. I added a class to increase the css specificity of my animations and reset and not it works. Please let me know if you have cleaner approach, otherwise feel free to close this issue 👍 
```tsx
cn(
    `
    !duration-200 
	// add custom class to increase specificity
	remove-vaul-animation
	// appen custom classe to desired animations
    [&.remove-vaul-animation[data-state="closed"]]:animate-out
    [&.remove-vaul-animation[data-state="closed"]]:fade-out-0
    [&.remove-vaul-animation[data-state="open"]]:animate-in
    [&.remove-vaul-animation[data-state="open"]]:fade-in-0
	// remove vaul animation
    [&.remove-vaul-animation]:animate-none
    [&.remove-vaul-animation[data-state="closed"]]:animate-none
`);
```

**Comment by emilkowalski** [comment]
I haven't thought about this, but this seems like a nice solution!

**Comment by Southclaws** [comment]
Hi @JeffreyJoumjian I'd like to implement this, but I'm not familiar with this `cn` syntax in your reply - is there a pure CSS equivalent you could share of what's being achieved here?

**Comment by emilkowalski** [comment]
@Southclaws cn joins your classnames, see this https://www.npmjs.com/package/classnames

**Comment by JeffreyJoumjian** [comment]
@Southclaws I did try doing it with css at one point. Basically I had one class that I applied and added the styles i wanted there so:
```css
.drawer {
	all: unset;
	/* if you're using tailwind, you can still use the @apply directive to apply tailwind classess */
	/* it also supports breakpoints but creates lots of weird styles and classes so i would avoid it */
	@apply data-[state=open]:animate-in data-[state=closed]:animate-out

	/* or write simple plain css, i don't know if you can refer to animate classes in there however */
	animation-duration: 200ms
}
```

Although I didn't this issue as it was already closed, when i packed the drawer with these styles into an npm package and used it in another repo, the compiled styles were different and some vaul default styles were being applied. I was short on time so I ultimately decided to use shadcn's [Sheet](https://ui.shadcn.com/docs/components/sheet) component as it was just a lot simpler and already supports our needs, although not as smooth or mobile first as Emil's which is why I was drawn to it at first... Also I didn't know shadcn had a drawer because it was weird to name it Sheet 😭
